routes/web.php
<?php

use App\Http\Requests\ManageUserRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController')->name('home');
Route::redirect('/home', '/');

Route::get('spelen/zoek', [\App\Http\Controllers\SpelController::class, 'search'])
    ->name('spelen.zoek');
Route::get('spelen/{spel}/print', [\App\Http\Controllers\SpelController::class, 'print'])
    ->name('spelen.print');
Route::patch('spelen/{spel}/approve', [\App\Http\Controllers\SpelController::class, 'approve'])
    ->name('spelen.approve');
Route::patch('spelen/{spel}/deny', [\App\Http\Controllers\SpelController::class, 'deny'])
    ->name('spelen.deny');
Route::post('spelen/{spel}/love', [\App\Http\Controllers\SpelController::class, 'love'])
    ->name('spelen.love');
Route::get('spelen/export/{spel}', [\App\Http\Controllers\WordCreatorController::class, 'create'])
    ->name('spelen.export');
Route::get('spelen/{spel}/attachments', [\App\Http\Controllers\AttachmentController::class, 'show'])->name('spelen.attachments');
Route::post('spelen/{spel}/attachments', [\App\Http\Controllers\AttachmentController::class, 'store']);
Route::get('spelen/{spel}/attachments/{attachment}', [\App\Http\Controllers\AttachmentController::class, 'download'])->name('spelen.attachments.download');
Route::delete('spelen/{spel}/attachments/{attachment}', [\App\Http\Controllers\AttachmentController::class, 'destroy'])->name('spelen.attachments.delete');
Route::get('spelen/{spel}/addtogroup', [\App\Http\Controllers\SpelController::class, 'selectGroup'])->name('spelen.addtogroup');
Route::post('spelen/{spel}/addtogroup', [\App\Http\Controllers\SpelController::class, 'addToGroup']);
Route::post('spelen/{spel}/copy', [\App\Http\Controllers\SpelController::class, 'copy'])->name('spelen.copy');
Route::post('spelen/{spel}/clear-flags', [\App\Http\Controllers\SpelController::class, 'clearFlags'])->name('spelen.clear-flags');
Route::resource('spelen', 'SpelController')
    ->parameters(['spelen' => 'spel']);
Route::apiResource('spelen.comments', 'CommentController')
    ->parameters(['spelen' => 'spel']);

Route::resource('verbonden', 'VerbondController')
    ->parameters(['verbonden' => 'verbond']) // Laravel doesn't understand Dutch
    ->only('index', 'show');

Route::resource('categories', 'CategorieController')->only('show', 'store');

Route::post('terrein', [\App\Http\Controllers\TerreinController::class, 'store'])
    ->name('terrein.store')
    ->middleware('verified');
Route::get('terrein/{terrein}', [\App\Http\Controllers\TerreinController::class, 'terrein'])->name('terrein');

Route::patch('users/{user}/promote', [\App\Http\Controllers\UserController::class, 'promote'])
    ->name('users.promote');
Route::patch('users/{user}/demote', [\App\Http\Controllers\UserController::class, 'demote'])
    ->name('users.demote');
Route::patch('users/{user}/verify', [\App\Http\Controllers\UserController::class, 'verify'])
    ->name('users.verify');
Route::patch('users/{user}/unverify', [\App\Http\Controllers\UserController::class, 'unverify'])
    ->name('users.unverify');
Route::resource('users', 'UserController');

Route::get('admin', 'AdminController@index')
    ->name('admin');

Route::get('/groups/{group}/member', [\App\Http\Controllers\GroupController::class, 'newmember'])->name('groups.newmember');
Route::post('/groups/{group}/member', [\App\Http\Controllers\GroupController::class, 'addmember']);
Route::delete('/groups/{group}/member/{user}', [\App\Http\Controllers\GroupController::class, 'removemember'])->name('groups.member');
Route::delete('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'removegame'])->name('groups.game');
Route::get('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'editcomment'])->name('groups.editcomment');
Route::put('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'updatecomment'])->name('groups.updatecomment');
Route::resource('groups', 'GroupController');

Route::get('/migrate', [\App\Http\Controllers\MigrationController::class, 'index']);

Auth::routes(['verify' => true]);

resources/views/admin.blade.php
@extends('layouts.app')

@section('left-bar')
    @can('manage users')
        <section class="center">
            <h1>Gebruikers</h1>
            <a href="{{ route('users.index') }}">Alle gebruikers</a>
        </section>
    @endcan
@endsection

@section('content')
    @if ($tecontroleren->count() > 0)
        <section class="center">
            <h1>Goed te keuren spelen</h1>
            <ul>
                @foreach ($tecontroleren as $spel)
                    <li>
                        <a href="{{ route('spelen.show', $spel) }}">
                            {{ $spel->titel }}
                        </a>
                    </li>
                @endforeach
            </ul>
        </section>
    @endif

    @if ($reported->count() > 0)
        <section class="center">
            <h1>Gerapporteerde spelen</h1>
            <ul>
                @foreach($reported as $game)
                    <li>
                        <a href="{{ route('spelen.show', $game) }}">
                            {{ $game->titel }}
                        </a>
                    </li>
                @endforeach
            </ul>
        </section>
    @endif

    @if ($verborgen->count() > 0)
        <section class="center">
            <h1>Verborgen spelen</h1>
            <ul>
                @foreach ($verborgen as $spel)
                    <li>
                        <a href="{{ route('spelen.show', $spel) }}">
                            {{ $spel->titel }}
                        </a>
                    </li>
                @endforeach
            </ul>
        </section>
    @endif

    <section class="center">
        <h1>Terreinen</h1>

        <ul>
            @foreach ($terreinen as $terrein)
                <li><a href="{{ route('terrein', $terrein) }}">
                    {{ $terrein->naam }}
                </a></li>
            @endforeach
        </ul>
        <form action="{{ route('terrein.store') }}" method="post">
            @csrf
            <h3><label for="terreinnaam">Nieuw terrein</label></h3>
            <input placeholder="Naam van het nieuwe terrein" type="text" name="naam" id="terreinnaam">
            <div class="group">
                <button type="submit">Opslaan</button>
            </div>
        </form>
    </section>

    <section class="center">
        <h1>Categorieën</h1>
        <ul>
            @foreach ($categorieen as $categorie)
                <li><a href="{{ route('categories.show', $categorie) }}">
                    {{ $categorie->naam }}
                </a></li>
            @endforeach
        </ul>
        <form action="{{ route('categories.store') }}" method="post">
            @csrf
            <h3><label for="naam">Nieuwe categorie</label></h3>
            <input placeholder="Naam van de nieuwe categorie" type="text" name="naam" id="categorienaam">
            <div class="group">
                <button type="submit">Opslaan</button>
            </div>
        </form>
    </section>
@endsection

resources/views/terrein.blade.php
@extends('layouts.app')

@section('title', $terrein->naam)

@section('content')
    <section class="center">
        <h1>{{ $terrein->naam }}</h1>
        @if ($spelen->count() < 1)
            <p>
                Er zijn geen spelen in <em>{{ $terrein->naam }}</em>
            </p>
        @endif
    </section>

    @component('components.shortspelen', ['spelen' => $spelen])
    @endcomponent

@endsection

@section('right-bar')
    <section class="center">
        <h3>Alle Categorieën</h3>
        <ul class="plain">
            @foreach ($terreinen as $ter)
                <li><a href="{{ route('terrein', $ter) }}">{{ $ter->naam }}</a></li>
            @endforeach
        </ul>
    </section>
    <section class="center">
        <h3>Alle Terreinen</h3>
        <ul class="plain">
            @foreach ($terreinen as $ter)
                <li><a href="{{ route('terrein', $ter) }}">{{ $ter->naam }}</a></li>
            @endforeach
        </ul>
    </section>
@endsection