routes/web.php
<?php

use App\Http\Requests\ManageUserRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController')->name('home');
Route::redirect('/home', '/');

Route::get('spelen/zoek', [\App\Http\Controllers\SpelController::class, 'search'])
    ->name('spelen.zoek');
Route::get('spelen/{spel}/print', [\App\Http\Controllers\SpelController::class, 'print'])
    ->name('spelen.print');
Route::patch('spelen/{spel}/approve', [\App\Http\Controllers\SpelController::class, 'approve'])
    ->name('spelen.approve');
Route::patch('spelen/{spel}/deny', [\App\Http\Controllers\SpelController::class, 'deny'])
    ->name('spelen.deny');
Route::post('spelen/{spel}/love', [\App\Http\Controllers\SpelController::class, 'love'])
    ->name('spelen.love');
Route::get('spelen/export/{spel}', [\App\Http\Controllers\WordCreatorController::class, 'create'])
    ->name('spelen.export');
Route::get('spelen/{spel}/attachments', [\App\Http\Controllers\AttachmentController::class, 'show'])->name('spelen.attachments');
Route::post('spelen/{spel}/attachments', [\App\Http\Controllers\AttachmentController::class, 'store']);
Route::get('spelen/{spel}/attachments/{attachment}', [\App\Http\Controllers\AttachmentController::class, 'download'])->name('spelen.attachments.download');
Route::delete('spelen/{spel}/attachments/{attachment}', [\App\Http\Controllers\AttachmentController::class, 'destroy'])->name('spelen.attachments.delete');
Route::get('spelen/{spel}/addtogroup', [\App\Http\Controllers\SpelController::class, 'selectGroup'])->name('spelen.addtogroup');
Route::post('spelen/{spel}/addtogroup', [\App\Http\Controllers\SpelController::class, 'addToGroup']);
Route::post('spelen/{spel}/copy', [\App\Http\Controllers\SpelController::class, 'copy'])->name('spelen.copy');
Route::post('spelen/{spel}/clear-flags', [\App\Http\Controllers\SpelController::class, 'clearFlags'])->name('spelen.clear-flags');
Route::resource('spelen', 'SpelController')
    ->parameters(['spelen' => 'spel']);
Route::apiResource('spelen.comments', 'CommentController')
    ->parameters(['spelen' => 'spel']);

Route::resource('verbonden', 'VerbondController')
    ->parameters(['verbonden' => 'verbond']) // Laravel doesn't understand Dutch
    ->only('index', 'show');

Route::resource('categories', 'CategorieController')->only('show', 'store');

Route::post('terrein', [\App\Http\Controllers\TerreinController::class, 'store'])
    ->name('terrein.store')
    ->middleware('verified');
Route::get('terrein/{terrein}', [\App\Http\Controllers\TerreinController::class, 'terrein'])->name('terrein');

Route::patch('users/{user}/promote', [\App\Http\Controllers\UserController::class, 'promote'])
    ->name('users.promote');
Route::patch('users/{user}/demote', [\App\Http\Controllers\UserController::class, 'demote'])
    ->name('users.demote');
Route::patch('users/{user}/verify', [\App\Http\Controllers\UserController::class, 'verify'])
    ->name('users.verify');
Route::patch('users/{user}/unverify', [\App\Http\Controllers\UserController::class, 'unverify'])
    ->name('users.unverify');
Route::resource('users', 'UserController');

Route::get('admin', 'AdminController@index')
    ->name('admin');

Route::get('/groups/{group}/member', [\App\Http\Controllers\GroupController::class, 'newmember'])->name('groups.newmember');
Route::post('/groups/{group}/member', [\App\Http\Controllers\GroupController::class, 'addmember']);
Route::delete('/groups/{group}/member/{user}', [\App\Http\Controllers\GroupController::class, 'removemember'])->name('groups.member');
Route::delete('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'removegame'])->name('groups.game');
Route::get('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'editcomment'])->name('groups.editcomment');
Route::put('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'updatecomment'])->name('groups.updatecomment');
Route::resource('groups', 'GroupController');

Route::get('/migrate', [\App\Http\Controllers\MigrationController::class, 'index']);

Auth::routes(['verify' => true]);

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;
    use HasRoles;

    protected $fillable = [
        'name', 'email', 'password', 'verbond_id'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function spelen() {
        return $this->hasMany('App\Spel', 'maker');
    }

    public function favourites()
    {
        return $this->hasMany('App\Favourite', 'userId');
    }

    public function verbond()
    {
        return $this->belongsTo('App\Verbond');
    }

    public function groups()
    {
        return $this->belongsToMany('App\Group', 'group_members', 'user_id', 'group_id');
    }

    public function comments(): HasMany
    {
        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Hash;
use Gate;
use Illuminate\Http\Request;
use App\Http\Requests\ManageUserRequest;
use App\Http\Requests\EditProfileRequest;
use App\User;

class UserController extends Controller
{
    public function __construct() {
        $this->middleware('can:manage users')
             ->only(['index', 'promote', 'demote', 'verify', 'unverify']);
        $this->middleware('verified')
            ->except('show');
    }

    public function show(User $user) {
        return view('users.show')
            ->with('gebruiker', $user);
    }

    public function index() {
        $gebruikers = \App\User::with('spelen', 'verbond')->get();

        return view('users.index')
            ->with('gebruikers', $gebruikers);
    }

    public function promote(User $user) {
        $user->assignRole('moderator');
        return redirect()->route('users.show', ['user' => $user]);
    }

    public function demote(User $user) {
        $user->removeRole('moderator');
        return redirect()->route('users.show', ['user' => $user]);
    }

    public function verify(User $user) {
        $user->assignRole('verified');
        return redirect()->route('users.show', ['user' => $user]);
    }

    public function unverify(User $user) {
        $user->removeRole('verified');
        return redirect()->route('users.show', ['user' => $user]);
    }

    public function edit(User $user) {
        if (Gate::allows('edit-profile', $user)) {
            return view('users.edit')->with('user', $user);
        } else {
            return redirect()->route('users.show', ['user' => $user]);
        }
    }

    public function update(EditProfileRequest $request, User $user) {
        $data = $request->validated();

        if (!Hash::check($data['currentpassword'], $user->password) && Gate::denies('manage users')) {
            return redirect()->back()->withErrors(['currentpassword' => "Huidig wachtwoord is niet correct."]);
        }

        if ($request->has('password') && $data['password'] != null) {
            $user->password = bcrypt($data['password']);
        }

        $user->email = $data['email'];
        $user->verbond_id = $data['verbond_id'];
        $user->name = $data['name'];
        $user->save();

        return redirect()->route('users.show', ['user' => $user])->with('success', "Je profiel is aangepast.");
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="center">

        <h1>Wijzig je profiel</h1>

        <form method="POST" action="{{ route('users.update', $user) }}">
            @csrf
            @method('PUT')

            <label for="name">{{ __('Name') }}</label>
            <input id="name" type="text" class="{{ $errors->has('name') ? ' errorinput' : '' }}" name="name" value="{{ old('name', $user->name) }}" required autofocus>

            @if ($errors->has('name'))
                <div class="alert error" role="alert">
                    {{ $errors->first('name') }}
                </div>
            @endif

            <label for="email">{{ __('E-Mail Address') }}</label>
            <input id="email" type="email" class="{{ $errors->has('email') ? ' errorinput' : '' }}" name="email" value="{{ old('email', $user->email) }}" required>

            @if ($errors->has('email'))
                <div class="alert error" role="alert">
                    {{ $errors->first('email') }}
                </div>
            @endif

            <label for="verbond_id">Verbond</label>
            <select id="verbond_id" name="verbond_id">
                @foreach (\App\Verbond::all() as $verbond)
                    <option value="{{ $verbond->id }}" @if ($verbond->id == $user->verbond->id) selected @endif>
                        {{ $verbond->name }}
                    </option>
                @endforeach
            </select>

            @if ($errors->has('verbond_id'))
                <div class="alert error" role="alert">
                    {{ $errors->first('verbond_id') }}
                </div>
            @endif

            <label for="password">Nieuw Wachtwoord (leeg laten om ongewijzigd te laten)</label>
            <input id="password" type="password" class="{{ $errors->has('password') ? ' errorinput' : '' }}" name="password">

            @if ($errors->has('password'))
                <div class="alert error" role="alert">
                    {{ $errors->first('password') }}
                </div>
            @endif

            <label for="password-confirm">Bevestig nieuw paswoord</label>
            <input id="password-confirm" type="password" name="password_confirmation">

            <label for="currentpassword">Huidig wachtwoord</label>
            <input name="currentpassword" id="currentpassword" class="{{ $errors->has('currentpassword') ? 'errorinput' : '' }}" type="password" required/>

            @if ($errors->has('currentpassword'))
                <div class="alert error" role="alert">
                    {{ $errors->first('currentpassword') }}
                </span>
            @endif

            <div class="group">
                <button type="submit">
                    <span class="fas fa-save"></span>
                    {{ __('Save') }}
                </button>
            </div>
        </form>

    </section>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'Alle gebruikers')

@section('content')
    <section class="center">
        <h1>Alle gebruikers</h1>
        <table class="table">
            <thead>
                <th scope="col">Naam</th>
                <th scope="col">Verbond</th>
                <th scope="col">Aantal spelen</th>
                <th scope="col">E-mail geverifieerd</th>
                <th scope="col">E-mailadres</th>
            </thead>
            <tbody>
                @foreach($gebruikers as $gebruiker)
                    <tr>
                        <th scope="row">
                            @include('components.gebruiker')
                        </th>
                        <td>{{ $gebruiker->verbond->name }}</td>
                        <td>{{ $gebruiker->spelen()->count() }}</td>
                        <td>
                            @if (is_null($gebruiker->email_verified_at))
                                <span class="fas fa-times-circle"></span>
                            @else
                                <span class="far fa-check-circle"></span>
                            @endif
                        </td>
                        <td>
                            <a href="mailto:{{ $gebruiker->email }}">
                                {{ $gebruiker->email }}
                            </a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </section>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('title', $gebruiker->name)

    @section('content')
        <section class="center">
            <h1>
                @include('components.gebruiker')
            </h1>
            <p>
                Kazou <a href="{{ route('verbonden.show', $gebruiker->verbond) }}">
                {{ $gebruiker->verbond->name }}
                </a>
            </p>
            @can('manage users')
            <p>
                <a href="mailto://{{ $gebruiker->email }}">{{ $gebruiker->email }}</a>
            </p>
            @endcan
        </section>

        <section class="center">
            <h3>Favorieten</h3>
            <ul>
                @foreach ($gebruiker->favourites as $favourite)
                    @can('discover', $favourite->spel)
                        <li>
                            <a href="{{ route('spelen.show', $favourite->spel) }}">
                                {{ $favourite->spel->titel }}
                            </a>
                        </li>
                    @endcan
                @endforeach
            </ul>
        </section>

        <section class="center">
            <h3>Spelen door {{ $gebruiker->name }}</h3>
            <ul>
                @foreach($gebruiker->spelen as $spel)
                    @can('discover', $spel)
                    <li>
                        <a href="{{ route('spelen.show', $spel) }}">
                            {{$spel->titel}}
                        </a>
                    </li>
                    @endcan
                @endforeach
            </ul>
        </section>

        <section class="center">
            <h3>Groepen</h3>
            <ul>
                @foreach($gebruiker->groups as $group)
                    @can('view', $group)
                    <li>
                        <a href="{{ route('groups.show', $group) }}">
                            {{ $group->name }}
                        </a>
                    </li>
                    @endcan
                @endforeach
            </ul>
        </section>

    @endsection

    @can('manage users')
    @section('left-bar')
        <section class="center">
            @if ($gebruiker->hasRole('moderator'))
                <form method="post" action="{{ route('users.demote', $gebruiker) }}">
                    @csrf
                    @method('PATCH')
                    <button class="dark" type="submit">Maak gewone gebruiker</button>
                </form>
            @else
                <form method="post" action="{{ route('users.promote', $gebruiker) }}">
                    @csrf
                    @method('PATCH')
                    <button type="submit">Promoveer gebruiker</button>
                </form>
            @endif
            @if ($gebruiker->hasRole('verified'))
                <form method="post" action="{{ route('users.unverify', $gebruiker) }}">
                    @csrf
                    @method('PATCH')
                    <button type="submit">Onverifieer gebruiker</button>
                </form>
            @else
                <form method="post" action="{{ route('users.verify', $gebruiker) }}">
                    @csrf
                    @method('PATCH')
                    <button type="submit">Verifieer gebruiker</button>
                </form>
            @endif
        </section>
    @endsection
    @endcan

    @if (\Gate::allows('edit-profile', $gebruiker))
        @section('right-bar')
            <section class="center">
                <a class="btn primary" href="{{ route('users.edit', $gebruiker) }}">
                    <span class="fa fa-pencil-alt"></span> Bewerk profiel
                </a>
            </section>
        @endsection
    @endif