routes/web.php
<?php

use App\Http\Requests\ManageUserRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController')->name('home');
Route::redirect('/home', '/');

Route::get('spelen/zoek', [\App\Http\Controllers\SpelController::class, 'search'])
    ->name('spelen.zoek');
Route::get('spelen/{spel}/print', [\App\Http\Controllers\SpelController::class, 'print'])
    ->name('spelen.print');
Route::patch('spelen/{spel}/approve', [\App\Http\Controllers\SpelController::class, 'approve'])
    ->name('spelen.approve');
Route::patch('spelen/{spel}/deny', [\App\Http\Controllers\SpelController::class, 'deny'])
    ->name('spelen.deny');
Route::post('spelen/{spel}/love', [\App\Http\Controllers\SpelController::class, 'love'])
    ->name('spelen.love');
Route::get('spelen/export/{spel}', [\App\Http\Controllers\WordCreatorController::class, 'create'])
    ->name('spelen.export');
Route::get('spelen/{spel}/attachments', [\App\Http\Controllers\AttachmentController::class, 'show'])->name('spelen.attachments');
Route::post('spelen/{spel}/attachments', [\App\Http\Controllers\AttachmentController::class, 'store']);
Route::get('spelen/{spel}/attachments/{attachment}', [\App\Http\Controllers\AttachmentController::class, 'download'])->name('spelen.attachments.download');
Route::delete('spelen/{spel}/attachments/{attachment}', [\App\Http\Controllers\AttachmentController::class, 'destroy'])->name('spelen.attachments.delete');
Route::get('spelen/{spel}/addtogroup', [\App\Http\Controllers\SpelController::class, 'selectGroup'])->name('spelen.addtogroup');
Route::post('spelen/{spel}/addtogroup', [\App\Http\Controllers\SpelController::class, 'addToGroup']);
Route::post('spelen/{spel}/copy', [\App\Http\Controllers\SpelController::class, 'copy'])->name('spelen.copy');
Route::post('spelen/{spel}/clear-flags', [\App\Http\Controllers\SpelController::class, 'clearFlags'])->name('spelen.clear-flags');
Route::resource('spelen', 'SpelController')
    ->parameters(['spelen' => 'spel']);
Route::apiResource('spelen.comments', 'CommentController')
    ->parameters(['spelen' => 'spel']);

Route::resource('verbonden', 'VerbondController')
    ->parameters(['verbonden' => 'verbond']) // Laravel doesn't understand Dutch
    ->only('index', 'show');

Route::resource('categories', 'CategorieController')->only('show', 'store');

Route::post('terrein', [\App\Http\Controllers\TerreinController::class, 'store'])
    ->name('terrein.store')
    ->middleware('verified');
Route::get('terrein/{terrein}', [\App\Http\Controllers\TerreinController::class, 'terrein'])->name('terrein');

Route::patch('users/{user}/promote', [\App\Http\Controllers\UserController::class, 'promote'])
    ->name('users.promote');
Route::patch('users/{user}/demote', [\App\Http\Controllers\UserController::class, 'demote'])
    ->name('users.demote');
Route::patch('users/{user}/verify', [\App\Http\Controllers\UserController::class, 'verify'])
    ->name('users.verify');
Route::patch('users/{user}/unverify', [\App\Http\Controllers\UserController::class, 'unverify'])
    ->name('users.unverify');
Route::resource('users', 'UserController');

Route::get('admin', 'AdminController@index')
    ->name('admin');

Route::get('/groups/{group}/member', [\App\Http\Controllers\GroupController::class, 'newmember'])->name('groups.newmember');
Route::post('/groups/{group}/member', [\App\Http\Controllers\GroupController::class, 'addmember']);
Route::delete('/groups/{group}/member/{user}', [\App\Http\Controllers\GroupController::class, 'removemember'])->name('groups.member');
Route::delete('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'removegame'])->name('groups.game');
Route::get('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'editcomment'])->name('groups.editcomment');
Route::put('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'updatecomment'])->name('groups.updatecomment');
Route::resource('groups', 'GroupController');

Route::get('/migrate', [\App\Http\Controllers\MigrationController::class, 'index']);

Auth::routes(['verify' => true]);

app/Spel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Spel
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Spel newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Spel newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Spel query()
 * @mixin \Eloquent
 */
class Spel extends Model
{
    use SoftDeletes;

    protected $table = 'spelen';
    protected $fillable = [
        'titel', 'minLeeftijd', 'maxLeeftijd', 'categorieId', 'terreinId', 'uitleg', 'deelnemers', 'original_id',
        'duurMinuten', 'materiaal', 'monis', 'taakverdeling', 'inkleding', 'inclusie', 'isDraft', 'is_jomba',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo('App\User', 'maker');
    }

    public function categorie(): BelongsTo
    {
        return $this->belongsTo('App\Categorie', 'categorieId');
    }

    public function original(): BelongsTo
    {
        return $this->belongsTo('App\Spel');
    }

    public function derivatives(): HasMany
    {
        return $this->hasMany('App\Spel', 'original_id');
    }

    public function favourites(): HasMany
    {
        return $this->hasMany('App\Favourite', 'spelId');
    }

    public function terrein(): BelongsTo
    {
        return $this->belongsTo('App\Terrein', 'terreinId');
    }

    public function groups(): BelongsToMany
    {
        return $this->belongsToMany('App\Group', 'group_games', 'spel_id', 'group_id')
            ->withPivot('comment', 'scheduled');
    }

    public function attachments(): HasMany
    {
        return $this->hasMany('App\GameAttachment', 'game_id');
    }

    public function comments(): HasMany
    {
        return $this->hasMany('App\Comment', 'game_id');
    }

    public function getPublicAttribute(): bool
    {
        return $this->zichtbaar && $this->gecontroleerd && !($this->isDraft);
    }

    public function getVisibleByUrlAttribute(): bool
    {
        if ($this->gecontroleerd && ($this->zichtbaar == false)) {
            return false;
        }

        return true;
    }

    public function getFlaggedAttribute(): bool
    {
        return $this->comments()->where('flag', true)
                ->where('flag_removed_at', '=', null)
                ->count() > 0;
    }

    public static function boot() {
        parent::boot();

        static::deleting(function ($obj) {
            foreach($obj->favourites()->get() as $favourite) {
                $favourite->delete();
            }
        });

        static::restored(function ($obj) {
            foreach ($obj->favourites()->withTrashed()->get() as $favourite) {
                $favourite->restore();
            }
        });
    }
}

resources/views/spelen/addtogroup.blade.php
@extends('layouts.app')

@section('extra-header')
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
@endsection

@section('title'){{ $spel->titel }}@endsection

@section('content')
    <section class="center">
        <h1>Voeg dit spel toe aan een groep</h1>
        <form method="post" action="{{ route('spelen.addtogroup', ['spel' => $spel]) }}">
            @csrf
            <label for="group">Kies een groep</label>
            <select id="group" name="group">
                @foreach ($groups as $group)
                    <option value="{{ $group->id }}">{{ $group->name }}</option>
                @endforeach
            </select>

            @if ($errors->has('group'))
                <div class="alert error" role="alert">
                    {{ $errors->first('group') }}
                </div>
            @endif

            <label for="comment">Opmerking (optioneel)</label>
            <textarea style="resize:vertical;" cols="5" id="comment" name="comment" rows="5">{{ old('comment') }}</textarea>

            @if ($errors->has('comment'))
                <div class="alert error" role="alert">
                    {{ $errors->first('comment') }}
                </div>
            @endif

            <label for="scheduled">Wanneer is dit spel gepland? (optioneel)</label>
            <input id="scheduled" class="flatpickr flatpickr-input" name="scheduled" type="text" value="{{ old('scheduled') }}" readonly="readonly" />
            <label for="doschedule">Plan het spel?</label>
            <input name="doschedule" type="hidden" value="0"/>
            <input id="doschedule" name="doschedule" type="checkbox" value="1" />

            @if ($errors->has('scheduled'))
                <div class="alert error" role="alert">
                    {{ $errors->first('scheduled') }}
                </div>
            @endif

            <div class="group">
                <button type="submit">
                    <span class="fa fa-user-plus"></span> Voeg toe
                </button>
            </div>
        </form>
    </section>
@endsection

@section('scriptarea')
    <script>
        $(document).ready(function() {
            $('#group').select2();
            $('#scheduled').flatpickr({
                enableTime: true,
                dateFormat: "Y-m-d H:i",
                time_24hr: true,
            });
        });
    </script>
@endsection

resources/views/spelen/create.blade.php
@extends('layouts.app')

@section('title', 'Nieuw Spel')

@section('extra-header')
    <!-- EasyMDE -->
    <link rel="stylesheet" href="https://unpkg.com/easymde@2.10.1/dist/easymde.min.css">
    <script src="https://unpkg.com/easymde@2.10.1/dist/easymde.min.js"></script>
@endsection

@section('content')
    <section class="center">
        <h1>Nieuw Spel</h1>
        <p>
            Als je bent ingelogd, kan je achteraf je spel nog bewerken.
            Anders wordt dit spel opgeslagen als een anoniem spel.
        </p>
        <h3>TIA UND TIM</h3>
        <p>
            <b>T</b>errein, <b>I</b>nkleding, <b>A</b>antal deelnemers, <b>U</b>itleg, <b>N</b>aam, <b>D</b>uur, <b>T</b>aakverdeling, <b>I</b>nclusie, <b>M</b>ateriaal
        </p>
    </section>

    @if ($errors->any())
        <section class="alert error">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </section>
    @endif

    <form action="{{ route('spelen.index') }}" method="post">
        @csrf
        <section class="center">
            <h2>Titel</h2>
            <p>Dit is verplicht.</p>
            <input type="text" name="titel" id="titel" required value="{{ old('titel') }}">
        </section>

        <section class="center">
            <h2>Terrein</h2>
            <select name="terreinId" id="terrein">
                @foreach ($terreinen as $terrein)
                    <option value="{{ $terrein->id }}" @if($terrein->id == old('terreinId')) selected @endif>
                        {{ $terrein->naam }}
                    </option>
                @endforeach
            </select>
        </section>

        <section class="center">
            <h2>Categorie</h2>
            <select name="categorieId" id="categorie">
                @foreach ($categorieen as $categorie)
                    <option value="{{ $categorie->id }}" @if($categorie->id == old('categorieId')) selected @endif>
                        {{ $categorie->naam }}
                    </option>
                @endforeach
            </select>
        </section>

        <section class="center">
            <h2>Inkleding</h2>
            <textarea name="inkleding" id="inkleding" cols="80" rows="20">{{ old('inkleding') }}</textarea>
            <i>
                <a href="https://gitlab.com/WGCommunicatieWD/spelendatabase/wikis/gebruik/markdown" target="_blank">Help over opmaak</a>
            </i>
        </section>

        <section class="center">
            <h2>Aantal deelnemers</h2>
            <p>Een schatting is prima hier.</p>
            <p>Dit is verplicht.</p>
            <p>
                <input name="deelnemers" type="number" min="0" max="99" required value="{{ old('deelnemers') }}">
            </p>
            <h2>Leeftijd deelnemers</h2>
            <p>Dit is verplicht.</p>
            <input name="is_jomba" id="jomba" type="checkbox" value="1"/>
            <label for="jomba">JOMBA</label>
            <div class="wrapper">
                <div class="col-1">
                    <label for="minLeeftijd">Van</label>
                </div>
                <div class="col-4">
                    <input type="number" name="minLeeftijd" id="minLeeftijd" min="0" max="99" value="{{ old('minLeeftijd', 0) }}" required>
                </div>
                <div class="col-1">
                    <label for="maxLeeftijd">tot</label>
                </div>
                <div class="col-4">
                    <input type="number" name="maxLeeftijd" id="maxLeeftijd" min="0" max="99" value="{{ old('maxLeeftijd', 99) }}" required>
                </div>
                <div class="col-1">
                    jaar.
                </div>
            </div>
            <h2>Aantal moni's</h2>
            <p>Ongeveer is goed genoeg.</p>
            <input type="number" name="monis" min="0" max="99" value="{{ old('monis') }}">
        </section>

        <section class="center">
            <h2>Uitleg</h2>
            <p>Dit is verplicht.</p>
            <textarea name="uitleg" id="uitleg" cols="80" rows="50">{{ old('uitleg') }}</textarea>
            <i>
                <a href="https://gitlab.com/WGCommunicatieWD/spelendatabase/wikis/gebruik/markdown" target="_blank">Help over opmaak</a>
            </i>
        </section>

        <section class="center">
            <h2>Duur</h2>
            <p>In minuten, je mag gokken.</p>
            <p>Dit is verplicht.</p>
            <input type="number" name="duurMinuten" id="duurMinuten" min="0" max="65535" value="{{ old('duurMinuten', 90) }}" required>
        </section>

        <section class="center">
            <h2>Taakverdeling</h2>
            <textarea name="taakverdeling" id="taakverdeling" cols="80" rows="20">{{ old('taakverdeling') }}</textarea>
            <i>
                <a href="https://gitlab.com/WGCommunicatieWD/spelendatabase/wikis/gebruik/markdown" target="_blank">Help over opmaak</a>
            </i>
        </section>

        <section class="center">
            <h2>Inclusie</h2>
            <textarea name="inclusie" id="inclusie" cols="80" rows="20">{{ old('inclusie') }}</textarea>
            <i>
                <a href="https://gitlab.com/WGCommunicatieWD/spelendatabase/wikis/gebruik/markdown" target="_blank">Help over opmaak</a>
            </i>
        </section>

        <section class="center">
            <h2>Materiaal</h2>
            <textarea name="materiaal" id="materiaal" cols="80" rows="20">{{ old('materiaal') }}</textarea>
            <i>
                <a href="https://gitlab.com/WGCommunicatieWD/spelendatabase/wikis/gebruik/markdown" target="_blank">Help over opmaak</a>
            </i>
        </section>

        <section class="center">
            <h2>Klaar om te verzenden?</h2>
            <input name="isDraft" id="isDraft" type="checkbox" value="1" @if(old('isDraft')) checked @endif />
            <label for="isDraft"> Opslaan als klad</label>
            <div class="group">
                <button class="primary" save type="submit">
                    <span class="fa fa-save"></span>
                    Opslaan
                </button>
            </div>
        </section>
    </form>

@endsection

@section('scriptarea')
    <script>
        function genMDEConfig(id) {
            return {
                autosave: {
                    enabled: true,
                    delay: 5000,
                    uniqueId: id + "New",
                },
                promptURLs: true, forceSync: true, spellChecker: false, element: document.getElementById(id),
            };
        };

        var inkledingMDE = new EasyMDE(genMDEConfig("inkleding"));
        var uitlegMDE = new EasyMDE(genMDEConfig("uitleg"));
        var taakverdelingMDE = new EasyMDE(genMDEConfig("taakverdeling"));
        var inclusieMDE = new EasyMDE(genMDEConfig("inclusie"));
        var materiaalMDE = new EasyMDE(genMDEConfig("materiaal"));
    </script>
@endsection

resources/views/spelen/index.blade.php
@extends('layouts.app')

@section('title', 'Alle spelen')

@section('content')

    <section class="center">
        <h1>Alle spelen</h1>
        @if ($spelen->count() < 1)
            <p>
                Er zijn nog geen spelen toegevoegd...
            </p>
        @endif
    </section>

    @component('components.shortspelen', ['spelen' => $spelen])
    @endcomponent

@endsection

@section('right-bar')
    <section class="center">
        <h3>Alle Categorieën</h3>
        <ul class="plain">
            @foreach ($categorieen as $cat)
                <li>
                    <a href="{{ route('categories.show', $cat) }}">
                        {{ $cat->naam }}
                    </a>
                </li>
            @endforeach
        </ul>
    </section>

    <section class="center">
        <h3>Alle Terreinen</h3>
        <ul class="plain">
            @foreach ($terreinen as $cat)
                <li><a href="{{ route('terrein', $cat) }}">
                    {{ $cat->naam }}
                </a></li>
            @endforeach
        </ul>
    </section>
@endsection

resources/views/spelen/show.blade.php
@extends('layouts.app')

@section('extra-header')
    <!-- EasyMDE -->
    <link rel="stylesheet" href="https://unpkg.com/easymde@2.10.1/dist/easymde.min.css">
    <script src="https://unpkg.com/easymde@2.10.1/dist/easymde.min.js"></script>
@endsection

@section('title', $spel->titel)

    @section('left-bar')
        <section class="center">
            <a target="_blank" href="{{ route('spelen.print', $spel) }}" class="btn primary">
                <span class="fa fa-print"></span> Print
            </a>
            <a href="{{ route('spelen.export', $spel) }}" class="btn primary">
                <span class="fa fa-file-word"></span> Download
            </a>
            @auth
            <form class="d-inline" action="{{ route('spelen.copy', $spel) }}" method="post">
                @csrf
                <button class="primary" type="submit">
                    <span class="fas fa-copy"></span> Kopieer
                </button>
            </form>
            <a class="btn primary" href="{{ route('spelen.attachments', $spel) }}">
                <span class="fas fa-file"></span>
                Bijlagen
            </a>
            <a class="btn primary" href="{{ route('spelen.addtogroup', $spel) }}">
                <span class="fa fa-user-plus"></span> Voeg toe aan groep
            </a>
        </section>
        <section class="center">
            @endauth
            @can('approve games')
                @if (!$spel->zichtbaar)
                    <form action="{{ route('spelen.approve', $spel) }}" method="post" class="d-inline">
                        @csrf
                        @method('PATCH')
                        <button class="primary" type="submit">
                            <span class="fas fa-thumbs-up"></span>
                            Keur goed
                        </button>
                    </form>
                @else
                    <form action="{{ route('spelen.deny', $spel) }}" method="post">
                        @csrf
                        @method('PATCH')
                        <button class="dark" type="submit">
                            <span class="fas fa-thumbs-down"></span>
                            Keur af
                        </button>
                    </form>
                @endif
                @if ($spel->flagged)
                        <form action="{{ route('spelen.clear-flags', $spel) }}" method="post" class="d-inline">
                            @csrf
                            <button class="primary" type="submit">
                                <span class="far fa-flag"></span>
                                Verwijder flags
                            </button>
                        </form>
                @endif
            @endcan
            @can('manage-spel', $spel)
                <form action="{{ route('spelen.show', $spel) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="danger">
                        <span class="fas fa-trash"></span> Verwijder
                    </button>
                </form>
            @endcan
        </section>
    @endsection

    @section('content')
        <section class="center">
            <div class="wrapper">
                <div class="col-1">
                </div>
                <div class="col-2">
                    @include('components.game-badges')
                    <h1>
                        {{ $spel->titel }} @can('manage-spel', $spel)<a href="{{route('spelen.edit', ['spel' => $spel])}}"><i class="fa fa-pencil-alt"></i></a>@endcan
                    </h1>
                        @if($spel->isDraft) <h2>Klad</h2> @endif
                    @unless(is_null($spel->original))
                        @can('view', $spel->original)
                        <p>
                            Gebaseerd op <a href="{{ route('spelen.show', $spel->original) }}">{{ $spel->original->titel }}</a>
                        </p>
                        @endcan
                    @endunless

                    @unless (is_null($spel->maker))
                        <p>
                            <em>
                                Door @include('components.gebruiker', ['gebruiker' => $spel->user])
                            </em>
                        </p>
                    @endunless
                    <p>{{ $spel->views }} keer bekeken</p>
                </div>
                <div class="col-1">

                    @can('stem-spel', $spel)
                    @if ($loves)
                        <h2>
                            <form action="{{ route('spelen.love', $spel) }}" method="post">
                                @csrf
                                <button class="hart">
                                    {{ $spel->aantalStemmen }}
                                </button>
                            </form>
                        </h2>
                    @else
                        <h2>
                            <form action="{{ route('spelen.love', $spel) }}" method="post">
                                @csrf
                                <button class="hart-off">
                                    {{ $spel->aantalStemmen }}
                                </button>
                            </form>
                        </h2>
                    @endif
                    @endcan

                    @cannot('stem-spel', $spel)
                        <h2>
                            @csrf
                            <a class="hart-off hartoff">
                                {{ $spel->aantalStemmen }}
                            </a>
                        </h2>
                    @endcannot

                </div>
            </div>
        </section>



        @if (!is_null($spel->inkleding))
            <section class="center">
                <h2>Inkleding</h2>
                <div class="user-html">
                    @markdown($spel->inkleding)
                </div>
            </section>
        @endif

        <section class="center">
            <h2>Uitleg</h2>
            <div class="user-html">
                @markdown($spel->uitleg)
            </div>
        </section>

        @if (!is_null($spel->taakverdeling))
            <section class="center">
                <h2>Taakverdeling</h2>
                <div class="user-html">
                    @markdown($spel->taakverdeling)
                </div>
            </section>
        @endif

        @if (!is_null($spel->inclusie))
            <section class="center">
                <h2>Inclusie</h2>
                <div class="user-html">
                    @markdown($spel->inclusie)
                </div>
            </section>
        @endif

        @if (!is_null($spel->materiaal))
            <section class="center">
                <h2>Materiaal</h2>
                <div class="user-html">
                    @markdown($spel->materiaal)
                </div>
            </section>
        @endif

        @if ($spel->attachments->count() > 0)
            <section class="center">
                <h2>Bijlagen</h2>
                <ul>
                    @foreach ($spel->attachments as $a)
                        <li><a href="{{ route('spelen.attachments.download', ['spel'=>$spel,'attachment'=>$a]) }}">{{ $a->originalname }}</a></li>
                    @endforeach
                </ul>
            </section>
        @endif

        <hr>

        @foreach ($spel->comments as $comment)
            @can('view', $comment)
                <section class="inverted">
                    <h3>
                        {{ $comment->user->name }} <small>{{ $comment->created_at->shortRelativeDiffForHumans() }}</small>
                        @if ($comment->restricted_to_author)
                            <span class="fa fa-eye-slash" title="Enkel zichtbaar voor de auteur van dit spel."></span>
                        @endif
                        @if ($comment->flag && is_null($comment->flag_removed_at))
                            <span class="fas fa-flag" title="Gerapporteerd aan moderatoren"></span>
                        @elseif ($comment->flag && $comment->flag_removed_at != null)
                            <span class="far fa-flag" title="Gerapporteerd en gecontroleerd"></span>
                        @endif
                    </h3>
                    <div class="user-html">
                        @markdown($comment->content)
                    </div>
                </section>
            @endcan
        @endforeach

        <section class="inverted">
            <h2>Nieuwe reactie</h2>
            <form action="{{ route('spelen.comments.store', $spel) }}" method="post">
                @csrf
                <textarea name="content" id="comment-content" cols="30" rows="10"></textarea>
                <div class="group">
                    <input type="hidden" name="restricted_to_author" value="0">
                    <input type="checkbox" name="restricted_to_author" id="restricted_to_author" value="1">
                    <label for="restricted_to_author">Enkel zichtbaar voor de auteur?</label>
                </div>
                <div class="group">
                    <input type="hidden" name="flag" value="0">
                    <input type="checkbox" name="flag" id="flag" value="1">
                    <label for="flag">Rapporteer naar moderatoren?</label>
                </div>
                <div class="group">
                    <button class="primary" type="submit">
                        <span class="fa fa-save"></span>
                        Opslaan
                    </button>
                </div>
                <div class="group">
                    <i>Je kan dit niet meer bewerken later.</i>
                </div>
            </form>
        </section>

    @endsection

    @section('right-bar')
        <section class="center">
            <div class="wrapper">
                <div class="col-1">
                    @if (!is_null($spel->categorieId))
                        <h2>Categorie</h2>
                        <p><a href="{{route('categories.show', ['category'=>$spel->categorie])}}">
                            {{ $spel->categorie->naam }}</a></p>
                    @endif

                    <h2>Leeftijd</h2>
                    @if ($spel->is_jomba)
                        <p>JOMBA ({{ $spel->minLeeftijd }} - {{ $spel->maxLeeftijd }})</p>
                    @else
                        <p>Van {{ $spel->minLeeftijd }} tot {{ $spel->maxLeeftijd }} jaar.</p>
                    @endif

                    <h2>Aantal deelnemers</h2>

                    <p>Ongeveer {{ $spel->deelnemers }}</p>

                    <h2>Aantal moni's</h2>
                    @if($spel->monis == 1)
                        <p>
                            {{ $spel->monis }} moni
                        </p>
                    @else
                        <p>
                            {{ $spel->monis }} moni's
                        </p>
                    @endif

                    <h2>Duur</h2>
                    <p>{{ $spel->duurMinuten }} minuten</p>

                    @if (!is_null($spel->terreinId))
                        <h2>Terrein</h2>
                        <p><a href="{{ route('terrein', ['terrein' => $spel->terrein]) }}">{{ $spel->terrein->naam }}</a></p>
                    @endif

                </div>
            </div>
        </section>

        @unless ($spel->derivatives()->count() < 1)
            <section class="center">
                <h2>Afgeleide spelen</h2>
                <ul>
                    @foreach ($spel->derivatives as $derivative)
                        @can ('view', $derivative)
                        <li>
                            <a href="{{ route('spelen.show', $derivative) }}">
                                {{ $derivative->titel }}
                            </a>
                            @unless (is_null($derivative->user))
                                door @include('components.gebruiker', ['gebruiker' => $derivative->user])
                            @endunless
                        </li>
                        @endcan
                    @endforeach
                </ul>
            </section>
        @endunless
    @endsection
@section('scriptarea')
    <script>
        function genMDEConfig(id) {
            return {
                autosave: {
                    enabled: true,
                    delay: 5000,
                    uniqueId: id + "New",
                },
                promptURLs: true, forceSync: true, spellChecker: false, element: document.getElementById(id),
            };
        };

        var mde = new EasyMDE(genMDEConfig("comment-content"));
    </script>
@endsection