routes/web.php
<?php

use App\Http\Requests\ManageUserRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController')->name('home');
Route::redirect('/home', '/');

Route::get('spelen/zoek', [\App\Http\Controllers\SpelController::class, 'search'])
    ->name('spelen.zoek');
Route::get('spelen/{spel}/print', [\App\Http\Controllers\SpelController::class, 'print'])
    ->name('spelen.print');
Route::patch('spelen/{spel}/approve', [\App\Http\Controllers\SpelController::class, 'approve'])
    ->name('spelen.approve');
Route::patch('spelen/{spel}/deny', [\App\Http\Controllers\SpelController::class, 'deny'])
    ->name('spelen.deny');
Route::post('spelen/{spel}/love', [\App\Http\Controllers\SpelController::class, 'love'])
    ->name('spelen.love');
Route::get('spelen/export/{spel}', [\App\Http\Controllers\WordCreatorController::class, 'create'])
    ->name('spelen.export');
Route::get('spelen/{spel}/attachments', [\App\Http\Controllers\AttachmentController::class, 'show'])->name('spelen.attachments');
Route::post('spelen/{spel}/attachments', [\App\Http\Controllers\AttachmentController::class, 'store']);
Route::get('spelen/{spel}/attachments/{attachment}', [\App\Http\Controllers\AttachmentController::class, 'download'])->name('spelen.attachments.download');
Route::delete('spelen/{spel}/attachments/{attachment}', [\App\Http\Controllers\AttachmentController::class, 'destroy'])->name('spelen.attachments.delete');
Route::get('spelen/{spel}/addtogroup', [\App\Http\Controllers\SpelController::class, 'selectGroup'])->name('spelen.addtogroup');
Route::post('spelen/{spel}/addtogroup', [\App\Http\Controllers\SpelController::class, 'addToGroup']);
Route::post('spelen/{spel}/copy', [\App\Http\Controllers\SpelController::class, 'copy'])->name('spelen.copy');
Route::post('spelen/{spel}/clear-flags', [\App\Http\Controllers\SpelController::class, 'clearFlags'])->name('spelen.clear-flags');
Route::resource('spelen', 'SpelController')
    ->parameters(['spelen' => 'spel']);
Route::apiResource('spelen.comments', 'CommentController')
    ->parameters(['spelen' => 'spel']);

Route::resource('verbonden', 'VerbondController')
    ->parameters(['verbonden' => 'verbond']) // Laravel doesn't understand Dutch
    ->only('index', 'show');

Route::resource('categories', 'CategorieController')->only('show', 'store');

Route::post('terrein', [\App\Http\Controllers\TerreinController::class, 'store'])
    ->name('terrein.store')
    ->middleware('verified');
Route::get('terrein/{terrein}', [\App\Http\Controllers\TerreinController::class, 'terrein'])->name('terrein');

Route::patch('users/{user}/promote', [\App\Http\Controllers\UserController::class, 'promote'])
    ->name('users.promote');
Route::patch('users/{user}/demote', [\App\Http\Controllers\UserController::class, 'demote'])
    ->name('users.demote');
Route::patch('users/{user}/verify', [\App\Http\Controllers\UserController::class, 'verify'])
    ->name('users.verify');
Route::patch('users/{user}/unverify', [\App\Http\Controllers\UserController::class, 'unverify'])
    ->name('users.unverify');
Route::resource('users', 'UserController');

Route::get('admin', 'AdminController@index')
    ->name('admin');

Route::get('/groups/{group}/member', [\App\Http\Controllers\GroupController::class, 'newmember'])->name('groups.newmember');
Route::post('/groups/{group}/member', [\App\Http\Controllers\GroupController::class, 'addmember']);
Route::delete('/groups/{group}/member/{user}', [\App\Http\Controllers\GroupController::class, 'removemember'])->name('groups.member');
Route::delete('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'removegame'])->name('groups.game');
Route::get('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'editcomment'])->name('groups.editcomment');
Route::put('/groups/{group}/game/{spel}', [\App\Http\Controllers\GroupController::class, 'updatecomment'])->name('groups.updatecomment');
Route::resource('groups', 'GroupController');

Route::get('/migrate', [\App\Http\Controllers\MigrationController::class, 'index']);

Auth::routes(['verify' => true]);

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class Group extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'public', 'description'];

    public function members(): BelongsToMany
    {
        return $this->belongsToMany('App\User', 'group_members', 'group_id', 'user_id');
    }

    public function games(): BelongsToMany
    {
        return $this->belongsToMany('App\Spel', 'group_games', 'group_id', 'spel_id')
            ->withPivot('comment', 'scheduled');
    }

    public function hasUser(User $user): bool
    {
        return $this->members()->where('id', $user->id)->exists();
    }

    public function getVisibleGamesAttribute(): Collection
    {
        $allGames = $this->games()->orderBy('scheduled', 'asc')->get();

        if (Gate::allows('group-member', $this)) {
            // If you are a member, show all games
            return $allGames;
        } else {
            // If not, show only games you should be able to see
            // and no drafts
            return $allGames->filter(function($spel) {
                return Gate::allows('discover', $spel);
            });
        }
    }

    public static function visiblePaginated()
    {
        if (Auth::check() && Auth::user()->hasRole('admin')) {
            return Group::paginate(20);
        } elseif (Auth::check()) {
            return Group::where('public', true)->orWhereHas('members', function($query) {
                $query->where('id', '==', Auth::user()->id);
            })->paginate(20);
        } else {
            return Group::where('public', true)->paginate(20);
        }
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Group;
use App\Http\Requests\AddMemberRequest;
use App\Http\Requests\GroupStoreRequest;
use App\Http\Requests\UpdateCommentRequest;
use App\Spel;
use App\User;
use Gate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class GroupController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Group::class, 'group');
        $this->middleware('verified')->except(['index', 'show']);
        $this->middleware('can:update,group')->only([
            'newmember',
            'addmember',
            'removemember',
            'removegame',
            'editcomment',
            'updatecomment',
        ]);
    }

    public function index()
    {
        return view('groups.index')->with('groups', Group::visiblePaginated());
    }

    public function create()
    {
        return view('groups.new');
    }

    public function store(GroupStoreRequest $request)
    {
        $data = $request->validated();

        $group = Group::create(['name' => $data['name'], 'public' => $data['public']]);
        if ($data['description'] != null) {
            $group->description = $data['description'];
        }
        $group->save();
        $group->members()->save(Auth::user());
        return redirect()->route('groups.show', ['group' => $group]);
    }

    public function show(Group $group)
    {
        if (Gate::allows('update', $group)) {
            $candidates = \App\User::whereDoesntHave('groups', function ($query) use ($group) {
                $query->where('id', '=', $group->id);
            })->where('id', '!=', Auth::user()->id)->get();
            return view('groups.show')
                ->with('candidates', $candidates)
                ->with('group', $group);
        }
        return view('groups.show')->with('group', $group);
    }

    public function edit(Group $group)
    {
        return view('groups.edit')->with('group', $group);
    }

    public function update(GroupStoreRequest $request, Group $group)
    {
        $data = $request->validated();
        $group->name = $data['name'];
        $group->public = $data['public'];
        if ($data['description'] != null) {
            $group->description = $data['description'];
        }
        $group->save();

        return redirect()->route('groups.show', ['group' => $group])->with('success', 'Je wijzigingen zijn opgeslagen.');
    }

    public function newmember(Group $group)
    {
        $candidates = \App\User::whereDoesntHave('groups', function ($query) use ($group) {
            $query->where('id', '=', $group->id);
        })->where('id', '!=', Auth::user()->id)->get();
        return view('groups.newmember')
            ->with('group', $group)
            ->with('candidates', $candidates);
    }

    public function addmember(AddMemberRequest $request, Group $group)
    {
        $data = $request->validated();
        foreach ($data['users'] as $id) {
            $user = \App\User::find($id);
            $group->members()->attach($user);
        }

        return redirect()->route('groups.show', ['group' => $group]);
    }

    public function removegame(Request $request, Group $group, Spel $spel)
    {
        if ($group->games->where('id', '=', $spel->id)->count() < 1) {
            return redirect()
                ->route('groups.show', ['group' => $group]);
        }

        $group->games()->detach($spel);
        return redirect()
            ->route('groups.show', ['group' => $group])
            ->with('success', 'Het spel is uit de groep verwijderd.');
    }

    public function removemember(Request $request, Group $group, User $user)
    {
        if ($group->members->where('id', '=', $user->id)->count() < 1) {
            return redirect()
                ->route('groups.show', ['group' => $group]);
        }

        $group->members()->detach($user);
        return redirect()
            ->route('groups.show', ['group' => $group])
            ->with('success', 'De persoon is uit de groep verwijderd.');
    }

    public function editcomment(Group $group, Spel $spel)
    {
        $game = $group->games()->find($spel->id);
        return view('groups.editcomment')->with('group', $group)->with('game', $game);
    }

    public function updatecomment(UpdateCommentRequest $request, Group $group, Spel $spel)
    {
        $data = $request->validated();
        $game = $group->games()->find($spel->id);
        $game->pivot->comment = $data['comment'];
        if ($data['doschedule']) {
            $game->pivot->scheduled = $data['scheduled'];
        }
        $game->pivot->save();
        return redirect()->route('groups.show', ['group' => $group]);
    }
}

resources/views/groups/edit.blade.php
@extends('layouts.app')

@section('title', $group->name)

    @section('content')
        <section class="center">

            <h1>Bewerk groep</h1>

            <form method="POST" action="{{ route('groups.update', ['group' => $group]) }}">
                @csrf
                @method('PUT')

                <label for="name">{{ __('Name') }}</label>
                <input id="name" type="text" {{ $errors->has('name') ? ' errorinput' : '' }}" name="name" value="{{ old('name', $group->name) }}" required autofocus>

                @if ($errors->has('name'))
                    <div class="alert error" role="alert">
                        {{ $errors->first('name') }}
                    </div>
                @endif

                <label for="description">Beschrijving</label>
                <textarea style="resize:vertical;" @if($errors->has('description')) class="errorinput" @endif cols="80" rows="5" id="description" name="description">{{ old('description', $group->description) }}</textarea>

                    @if ($errors->has('description'))
                    <div class="alert error" role="alert">
                        {{ $errors->first('description') }}
                    </div>
                    @endif

                    <label for="public">Is de groep publiek?</label>
                    <input name="public" type="hidden" value="0"/>
                    <input name="public" type="checkbox" value="1" @if($group->public) checked @endif />

                    @if ($errors->has('public'))
                    <div class="alert error" role="alert">
                        {{ $errors->first('public') }}
                    </div>
                    @endif

                        <div class="group">
                            <button type="submit">
                                <span class="fas fa-save"></span>
                                Opslaan
                            </button>
                        </div>
            </form>

        </section>
    @endsection

resources/views/groups/editcomment.blade.php
@extends('layouts.app')

@section('title', $group->name)

    @section('extra-header')
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    @endsection

    @section('content')
        <section class="center">

            <h1>Bewerk opmerking voor {{ $game->titel }}</h1>

            <form method="POST" action="{{ route('groups.updatecomment', ['group' => $group, 'spel' => $game]) }}">
                @csrf
                @method('PUT')

                <label for="comment">Opmerking</label>
                <textarea style="resize:vertical;" @if($errors->has('comment')) class="errorinput" @endif cols="80" rows="5" id="comment" name="comment">{{ old('description', $game->pivot->comment) }}</textarea>

                    @if ($errors->has('comment'))
                    <div class="alert error" role="alert">
                        {{ $errors->first('comment') }}
                    </div>
                    @endif

                    <label for="scheduled">Wanneer is dit spel gepland? (optioneel)</label>
                    <input id="scheduled" class="flatpickr flatpickr-input" name="scheduled" type="text" value="{{ old('scheduled', $game->pivot->scheduled) }}" readonly="readonly" />
                    <label for="doschedule">Plan het spel?</label>
                    <input name="doschedule" type="hidden" value="0"/>
                    <input id="doschedule" name="doschedule" type="checkbox" value="1" @if (old('doschedule', $game->pivot->scheduled != null)) checked @endif/>

                        @if ($errors->has('scheduled'))
                    <div class="alert error" role="alert">
                        {{ $errors->first('scheduled') }}
                    </div>
                        @endif

                        <div class="group">
                            <button type="submit">
                                <span class="fas fa-save"></span>
                                Opslaan
                            </button>
                        </div>
            </form>

        @endcomponent
    @endsection

    @section('scriptarea')
        <script>
            $(document).ready(function() {
                $('#scheduled').flatpickr({
                    enableTime: true,
                    dateFormat: "Y-m-d H:i",
                    time_24hr: true,
                });
            });
        </script>
    @endsection

resources/views/groups/index.blade.php
@extends('layouts.app')

@section('title', 'Groepen')

@section('content')
    <section class="center">
        <h1>Alle groepen</h1>
        @auth
        <a class="btn primary" href="{{ route('groups.create') }}">Nieuwe groep</a>
        @endauth
    </section>

    @component('components.shortgroups', ['groups' => $groups])
    @endcomponent
@endsection

resources/views/groups/new.blade.php
@extends('layouts.app')

@section('title', 'Nieuwe Groep')

@section('content')
    <section class="center">
        <h1>Nieuwe groep</h1>

        <form method="POST" action="{{ route('groups.store') }}">
            @csrf

            <label for="name">{{ __('Name') }}</label>
            <input id="name" type="text" class="{{ $errors->has('name') ? ' errorinput' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

            @if ($errors->has('name'))
                <div class="alert error" role="alert">
                    {{ $errors->first('name') }}
                </div>
            @endif

            <label for="description">Beschrijving</label>
            <textarea style="resize:vertical;" @if($errors->has('description')) class="errorinput" @endif cols="80" rows="5" id="description" name="description">{{ old('description') }}</textarea>

                @if ($errors->has('description'))
                <div class="alert error" role="alert">
                    {{ $errors->first('description') }}
                </div>
                @endif

                <label for="public">Is de groep publiek?</label>
                <input name="public" type="hidden" value="0"/>
                <input name="public" type="checkbox" value="1"/>

                @if ($errors->has('public'))
                    <div class="alert error" role="alert">
                        {{ $errors->first('public') }}
                    </div>
                @endif

                <p>
                    Je kan later leden toevoegen aan je groep.
                </p>

                <div class="group">
                    <button type="submit">
                        <span class="fas fa-save"></span>
                        Opslaan
                    </button>
                </div>
        </form>
    </section>
@endsection

resources/views/groups/newmember.blade.php
@extends('layouts.app')

@section('extra-header')
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
@endsection

@section('title'){{ $group->name }}@endsection

@section('content')
    <section class="center">
        <h1>Voeg een lid toe aan {{ $group->name }}</h1>
        <form method="post" action="{{ route('groups.newmember', $group) }}">
            @csrf
            <label for="users[]">Kies een of meerdere gebruikers</label>
            <select id="users" name="users[]" multiple="multiple">
                @foreach ($candidates as $candidate)
                    <option value="{{ $candidate->id }}">{{ $candidate->name }}</option>
                @endforeach
            </select>

            @if ($errors->has('users[]'))
                <div class="alert error" role="alert">
                    {{ $errors->first('users[]') }}
                </div>
            @endif

            <div class="group">
                <button type="submit"><i class="fa fa-user-plus"></i> Voeg toe</button>
            </div>
        </form>
    </section>
@endsection

@section('scriptarea')
    <script>
        $(document).ready(function() {
            $('#users').select2();
        });
    </script>
@endsection

resources/views/groups/show.blade.php
@extends('layouts.app')

@section('title'){{ $group->name }}@endsection

@section('content')
    <section class="center">
        <h1>{{ $group->name }}</h1>
        <p>
            {{ $group->description }}
        </p>
        <p>
            Je kan een spel toevoegen vanuit de spelpagina.
        </p>
    </section>

    @foreach ($group->visibleGames as $game)
        <section class="center">
            <h2>
                <a href="{{route('spelen.show', $game)}}">
                    {{ $game->titel }}
                </a>
                @can('update', $group)
                    <a href="{{ route('groups.editcomment', ['group' => $group, 'spel' => $game]) }}">
                        <span class="fa fa-pencil-alt"></span>
                    </a>
                @endcan
            </h2>
            @unless (is_null($game->maker))
                <p>
                    <em>Door @include('components.gebruiker', ['gebruiker' => $game->user])</em>
                </p>
            @endunless
            <p>
                {{ $game->duurMinuten }} minuten, {{ $game->deelnemers }} deelnemers
            </p>
            @unless(is_null($game->pivot->scheduled))
                <p>
                    Gepland op: {{ $game->pivot->scheduled }}
                </p>
            @endunless
            @unless (is_null($game->pivot->comment))
                <p>
                    {{ $game->pivot->comment }}
                </p>
            @endunless
            <p><a href="{{ route('spelen.show', $game) }}">Lees meer...</a></p>
            <form class="d-inline" action="{{ route('groups.game', ['group' => $group, 'spel' => $game]) }}"
                  method="post">
                @method('DELETE')
                @csrf
                <div class="group">
                    <button class="danger" type="submit">
                        <span class="fas fa-trash-alt"></span>
                    </button>
                </div>
            </form>
        </section>
    @endforeach
@endsection

@section('right-bar')
    <section class="center">
        <h2>Leden</h2>
        <ul>
            @foreach ($group->members as $member)
                @can('update', $group)
                    <form method="post" action="{{ route('groups.member', ['group' => $group, 'user' => $member]) }}">
                        @csrf
                        @method('DELETE')
                        <li>
                            <a href="{{ route('users.show', $member) }}">
                                {{ $member->name }}
                            </a>
                            <button type="submit" class="transparent danger">
                                <span class="fas fa-trash-alt"></span>
                            </button>
                        </li>
                    </form>
                @else
                    <li>
                        <a href="{{ route('users.show', $member) }}">
                            {{ $member->name }}
                        </a>
                    </li>
                @endcan
            @endforeach
        </ul>
        @can('update', $group)
            <p>
                @if (false)
                    <a class="btn primary" href="{{ route('groups.newmember', $group) }}">
                        <span class="fa fa-user-plus"></span> Voeg gebruiker toe
                    </a>
                @endif
                <add-user-to-group
                    :options='@json($candidates)'
                    name="users[]"
                    href="{{ route('groups.newmember', $group) }}"
                ></add-user-to-group>
            </p>
        @endcan
    </section>
@endsection

@can('update', $group)
@section('left-bar')
    <section class="center">
        <p>
            <a class="btn primary" href="{{ route('groups.edit', $group) }}">
                <span class="fa fa-pencil-alt"></span> Bewerk deze groep
            </a>
        </p>
    </section>
@endsection
@endcan